### PR TITLE
lua_typename now uses lua_type (fixes #16)

### LINKED ISSUE #16: lua_typename should use lua_type
In `readIntoFunction`, `lua_typename` should be using `lua_type` instead of `index`. This is currently causing segmentation faults when an invalid argument type is passed to a bound c++ function.

### PR DESCRIPTION
**Pull request by ecorm**
See #16.

### CODE REVIEW

**Comment by Habbie** [comment]
Want to write a test for this? If you rebase onto master, the testing framework works again and Travis will test the PR.

**Comment by ecorm** [comment]
I'll look into how complicated/understandable the tests are and will get back to you.

**Comment by Habbie** [comment]
Great! If you get stuck, let me know, I'm happy to give it a shot as well.

**Comment by Habbie** [comment]
Merged as part of #30, thanks!

**Pull request closed without merging**
