### PR TITLE
gather Lua tracebacks when an error happens

### PR DESCRIPTION
**Pull request by Habbie**

### CODE REVIEW

**Comment by Habbie** [comment]
This works for Lua errors (because those are strings), but if the error is some other object (like an exception from C++), `debug.traceback` just passes the object on without adding the traceback.

**Comment by Habbie** [comment]
Travis unhappy, need to investigate.

Also need to look at `rawseti` suggestion I got.

**Comment by ahupowerdns** [comment]
The test failures have to do with "the wrong kind of exception". However this only happens in 5.1.

**Comment by Habbie** [comment]
> The test failures have to do with "the wrong kind of exception". However this only happens in 5.1.

Finally got around to looking at this - `debug.traceback(nil, 2)` returns `nil` in Lua 5.1 instead of the expected traceback. I have now fixed this by calling `debug.traceback('', 2)` instead which appears to be portable between at least 5.1 and 5.2.

**Comment by Habbie** [comment]
rebased

**Pull request merged**
